# review-epubmaker向けの設定ファイルの例。
# yamlファイルをRe:VIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: book
booktitle: Androidクイックスタート
aut: 宮川大輔
prt: もわねっと
prt_url:  https://mowa-net.jp
edt: 宮川大輔
date: 2014-04-10
rights: |
  (C) 2014 Daisuke Miyakawa
description: 
# 以下はオプション
# prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
coverfile: _cover.html
# coverimage: 表紙用画像ファイル
coverimage: null
# 固有IDに使用するドメイン
urnid: http://mowa-net.jp
# CSSファイル (yamlファイルおよびRe:VIEWファイルを置いたディレクトリにあること
stylesheet: main.css
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 3
# review-compileに渡すパラメータ
params: --stylesheet=main.css
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: true
texstyle: reviewmacro
pubhistory: |
  2014年04月10日 v0.1発行
debug: True
